### ISSUE TITLE
Сверстать страницу клиентов

### ISSUE THREAD

**Issue by AndreyIo0I** [AndreyIo0I/furniture-helper#10]
[Примерный дизайн](https://www.figma.com/file/dfyeU4cz49To96SZdHQF3H/FURH-base?node-id=15%3A331&t=8C4e32zmjXeImMtv-0)

**Comment by sergoio0704** [comment]
Готово
https://github.com/AndreyIo0I/furniture-helper/pull/22/commits/e1e6ec91bac03c87f9b867318eb484fceff357ad
