### ISSUE TITLE
Проблемки на беке

### ISSUE THREAD

**Issue by AndreyIo0I** [AndreyIo0I/furniture-helper#47]
Не факт конечно что проблема именно на беке, мб в запросе что-то не то уходит, но беку тут виднее
- [x] 500 при смене пароля
- [x] не срабатывает завершение проекта
- [x] опционально: сейчас можно удалить клиента и проект останется без него, мб в проект записывать копию или удалять в таких случаях только из списка клиентов
- [x] после каждого изменения этапы проекта приходят в новом порядке

**Comment by algolGuru** [comment]
2 пункт: не срабатывает завершение проекта
 Проверил локально. 
![image](https://user-images.githubusercontent.com/61578859/215284640-41575df7-33b6-4259-99dd-40169865e7f8.png)
![image](https://user-images.githubusercontent.com/61578859/215284654-31c0f868-ff61-4fda-ba19-e7eca353521c.png)
![image](https://user-images.githubusercontent.com/61578859/215284657-43155725-f8d9-4e07-a712-967a7faf8c04.png)

Работает коректно

**Comment by algolGuru** [comment]
По 2 пункту локально проверил
Пароль корректно обновился
![image](https://user-images.githubusercontent.com/61578859/215284758-f19e3b48-40dc-4bad-89c1-e330bad64ed2.png)
![image](https://user-images.githubusercontent.com/61578859/215284765-e23bfd3e-9e5f-4b06-ba77-a696cfe3d1aa.png)

**Comment by algolGuru** [comment]
после каждого изменения этапы проекта приходят в новом порядке
Вроде как проверил, приходит корректно несмотря на обновление, но у них id в любом случае правильные остаются для 1 проекта:" от 1 до 14
![image](https://user-images.githubusercontent.com/61578859/215285098-d26af223-04d0-4d6d-92ac-a8733ae4d427.png)

**Comment by algolGuru** [comment]
опционально: сейчас можно удалить клиента и проект останется без него, мб в проект записывать копию или удалять в таких случаях только из списка клиентов
Сделано!
Если есть такой клиент, который используется в проектах, пишу невозможно удалить так как используется
ПОэтому если захотят надо удалять проект потом клиента
Так как удаление клиента вне зависимости от проектов это не консистентно
