### ISSUE TITLE
Сверстать страницу общих настроек проекта

### ISSUE THREAD

**Issue by AndreyIo0I** [AndreyIo0I/furniture-helper#5]
[Примерный дизайн](https://www.figma.com/file/dfyeU4cz49To96SZdHQF3H/FURH-base?node-id=14%3A109&t=8C4e32zmjXeImMtv-0)

**Comment by sergoio0704** [comment]
Готово https://github.com/AndreyIo0I/furniture-helper/commit/181e27d5f4853f4c467c3ac592c43ade1547b378
